### ISSUE TITLE
Using fonts

### ISSUE THREAD

**Issue by tomfischerNL** [thujohn/pdf-l4#1]
Dear John,

Is there a possibility to use fonts in your module?

Thanks,

**Comment by thujohn** [comment]
Hi.

I tried and it works on my side.

1 - Add a "fonts" folder in /public
2 - Add your fonts
3 - Add @font-face {font-family:font_name;src:url(\'fonts/font_name.ttf\');} in your css style
4 - Add p {font-family:font_name;} in your css style

**Comment by tomfischerNL** [comment]
I will try that ;) thanks for your quick support!

**Comment by tomfischerNL** [comment]
It still does not work, where do you declare your CSS file? Normally I put it in the blade files.
But if I put it in my HTML variable, it still doesn't work. I have a seperate CSS file named css-pdf.css for the invoices.

**Comment by thujohn** [comment]
I added the style direct in the header

**Comment by thujohn** [comment]
Here is a working example :

``` php
Route::get('/', function()
{
    $html = '<html>
            <header>
                <style>
                    @font-face {font-family:my_font;src:url(\'fonts/coolvetica rg.ttf\');}
                    p {font-family:my_font;}
                </style>
            </header>
            <body>
                <p>Put your html here, or generate it with your favourite templating system.</p>
            </body>
            </html>';
    return PDF::load($html, 'A4', 'portrait')->show();
});
```

Font : http://www.dafont.com/fr/coolvetica.font

**Comment by torsak** [comment]
Hello John,

I've got a problem adding font-face to work with PDF-L4 version 1.0.5. I've already set directory thujohn/pdf/src/Thujohn/Pdf/dompdf/lib/**fonts** to 777. See error message below.

```
file_put_contents(/root_dir/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/lib/fonts/dompdf_font_family_cache.dist.php): failed to open stream: Permission denied
```

or

```
file_put_contents(/root_dir/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/lib/fonts/1bd150f9aa8f4a8ba11ba347a469d3f0.ttf): failed to open stream: Permission denied
```

This is css code.

```
<head>
....
<style>
@font-face {
    font-family: 'Conv_MyriadPro-It';
    src: url('fonts/MyriadPro-It.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'shardeeregular';
    src: url('fonts/shardee.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
</style>
...
</head>
```

I came across this by setting file and directory permission to allow web server to write them.

```
cd vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/lib
chmod 777 fonts
cd fonts
chmod 777 dompdf_font_family_cache.dist.php
```

Do we need to do this to get font-face up and running?

Thanks!

**Comment by thujohn** [comment]
Hi.

If you check my first comment you can see : Add a "fonts" folder in /public
They shouldn't go to the vendor…

**Comment by torsak** [comment]
Hi John,

Thanks for your quick reply.

Yes. I already have a /public/fonts folder. It looks like this.

```
$ ls -l public/fonts
total 1224
-rwxr-xr-x  1 torsak  staff  119612 Mar 16 16:12 MyriadPro-It.eot
-rwxr-xr-x  1 torsak  staff   98064 Mar 16 16:12 MyriadPro-It.svg
-rwxr-xr-x  1 torsak  staff  119340 Mar 16 16:12 MyriadPro-It.ttf
-rwxr-xr-x  1 torsak  staff   66012 Mar 16 16:12 MyriadPro-It.woff
-rwxr-xr-x  1 torsak  staff   24289 Mar 16 16:12 shardee.eot
-rwxr-xr-x  1 torsak  staff   96970 Mar 16 16:12 shardee.svg
-rwxr-xr-x  1 torsak  staff   60640 Mar 16 16:12 shardee.ttf
-rwxr-xr-x  1 torsak  staff   28348 Mar 16 16:12 shardee.woff
```

But it seems that the PDF-L4 is trying to copy fonts from /public to /vendor folder. Is that a proper functional?

**Comment by brazorf** [comment]
Hey there
Why has this issue been closed? 

I've a similar issue: when my html template contains a <link> to an external font (google fonts), the library is probably trying to download it to its vendor directory, therefore triggering a _permission denied_ error since the web sever user can't access outside the public directory.

How to avoid this to happen?
