### ISSUE TITLE
Call to undefined method Thujohn\Pdf\PdfServiceProvider::package()

### ISSUE THREAD

**Issue by danny-den** [thujohn/pdf-l4#113]
Hi,
I am ussing Laravel version 5.3.30 trying to make pdf but i can't get past this error.
I did the following set up:
'providers' => array(
    Thujohn\Pdf\PdfServiceProvider::class,
)
'aliases' => array(
    'PDF' => Thujohn\Pdf\PdfFacade::class,
)

But 'php artisan config:publish thujohn/pdf' fails because can't find package method.
I did set chmod -R 777 to that folder.

Please any help would be appriciated.

**Comment by alex021925** [comment]
Comment line 21 in 'vendor\thujohn\pdf\src\Thujohn\Pdf\PdfServiceProvider.php'

/**
	 * Bootstrap the application events.
	 *
	 * @return void
	 */
	public function boot()
	{
//		$this->package('thujohn/pdf');
	}

It is bad practice but work...
