### ISSUE TITLE
Streaming with a passed filename

### ISSUE THREAD

**Issue by wdulaney** [thujohn/pdf-l4#14]
Thank you for the great, great job you've done putting this package together. It's the only one I've been able to get to work as expected with L4.

This isn't really an issue, but it would be fantastic if I could show() a PDF with a custom filename instead of the default 'dompdf_out.pdf'

Can you add a method that mirrors dompdf's stream() method where the user can pass a filename to use as the default? Something like:

public function stream($filename = 'dompdf_out'){
    $this->render();
    return $this->dompdf->stream($filename.'.pdf', array('compress' => 1, 'Attachment' => 0));
}

Thanks again!

**Comment by thujohn** [comment]
Hi.

You can use `download()` with your options : https://github.com/thujohn/pdf-l4/blob/master/src/Thujohn/Pdf/Pdf.php#L48

**Comment by wdulaney** [comment]
Of course, just set 'Attachment' => 0. Thanks!
