### ISSUE TITLE
Save generated PDF to a file on server

### ISSUE THREAD

**Issue by w0rldart** [thujohn/pdf-l4#16]
Is there anyway of generating a PDF, and save it to a file located in the app's folder, instead of being downloaded, shown or outputted as a string?

**Comment by w0rldart** [comment]
I actually managed to achieve my purpose with the following code:

```
$path = public_path().'/assets/test.pdf';
File::put($path, PDF::load($view, 'A4', 'portrait')->output());
```

**Comment by thujohn** [comment]
You can create a pull request if you want :)

**Comment by w0rldart** [comment]
I just did! Hope you find the information, useful! :)

**Comment by thujohn** [comment]
I created a section with your example in the readme.

Thank you :)

**Comment by Burnett01** [comment]
:+1:
