### ISSUE TITLE
Constant DOMPDF_TEMP_DIR already defined

### ISSUE THREAD

**Issue by HVSoftware** [thujohn/pdf-l4#22]
I get the error: Constant DOMPDF_TEMP_DIR already defined. I solved it partly.

//Just some sample code on how I use it

$invoices = Invoices::All()
foreach ($invoices as $invoice)
{
    // The error occured here when the second invoice is handled
    $dompdf = new \Thujohn\Pdf\Pdf();
    $dompdf->load($invoice->asHtml);
    $pdf = $dompdf->output();

```
// First one succesfull
```

}

Inside the Pdf.php file I've added the !defined. 

```
if (!defined($conf)) {
  define($conf, Config::get('pdf::'.$conf));
}
```

After this I get this error.

  [ErrorException]
  unlink(C:\Users\HVSsoftware\AppData\Local\Temp\ca_742.tmp): No such file or
   directory

Now I have solved it by generating one invoice at the time. Any other suggestions?

**Comment by HVSoftware** [comment]
inside the file src/Thujhon/pdf/dompdf/include/image_cache.cls.php

line 152. 
      if (file_exists($file)) {
        unlink($file);
      }

This solved the problem.

**Comment by thujohn** [comment]
I only added a !defined() verification.

Does it solve your problem ?

I don't have problem with temporary file...

What do you do with output ?

**Comment by HVSoftware** [comment]
I see you have used the pull-request. https://github.com/thujohn/pdf-l4/pull/23. Git is Cool. 
The !defined() solved the 'not defined' error. Thanks.

I'm writing the output to a file. This file has an inline image.

**Comment by thujohn** [comment]
Finally this problem is solved for me.

Only unlink($file) was not good. In my local example I wrote the same image and the image in the cache was cleared so Dompdf found it only the first time...

Now when you use the output() method you need to clear the cache manually because I deactivated it in the render() method directly in Dompdf.

Here is my example :

``` php
for ($i=1;$i<=2;$i++)
{
    $pdf = new \Thujohn\Pdf\Pdf();
    $content = $pdf->load(View::make('pdf.image'))->output();
    File::put(public_path('test'.$i.'.pdf'), $content);
}
PDF::clear();
```

**Comment by HVSoftware** [comment]
Solved this.

**Comment by dud3** [comment]
Cool this works for small tables, but it runs into infinite loop or similar on big tables, and times out.

**Comment by dustingraham** [comment]
@thujohn I just encountered this error as well. Might include that in the docs since the last example won't work if creating 2 or more PDF's.

Using the `$pdf = new Pdf();` each loop was the solution.

**Comment by jeanfbs** [comment]
Hi, how i generate an PDF with multiples page for only one file?
Example: I have a table that return 100 results, and i want the same file is shown two pages with 40 results
