### ISSUE TITLE
Add page to PDF

### ISSUE THREAD

**Issue by fastnsilent** [thujohn/pdf-l4#26]
How to add more pages to PDF file, i've already tried to run the example script, but it just showed only one page. Thanks..

**Comment by thujohn** [comment]
Hi.

Dompdf automatically adds pages as you can see in this example : http://lab.packalyst.com/pdf/utf8

**Comment by fastnsilent** [comment]
Ok, it's great.. thanks for your help..

**Comment by johnmax11** [comment]
hi.... have new --> tag html ---> (html---body...../body---/html) and 'EUREKA' set new page

**Comment by n3uromanc3r** [comment]
For anyone still having issues with this, as it is not entirely clear, each page needs a new BODY tag.

So, the following would produce 3 pages:

```
<html>
    <body></body>
    <body></body>
    <body></body>
</html>
```

**Comment by Chiaparini** [comment]
@n3uromanc3r Thanks man! You saved me.

**Comment by n3uromanc3r** [comment]
@Chiaparini glad it helped! :+1:
