### ISSUE TITLE
Multiple PDFs

### ISSUE THREAD

**Issue by itsjustk** [thujohn/pdf-l4#27]
The library is working fine when generating a single PDF, however when generating two in succession I always get the "no block-level parent found" error, on the second generation, the first PDF is generated fine without incident. 
I've tried using the library in different ways (creating a class and using one object for each PDF, not even using the laravel autoloader etc) and have used PDF::clear(), but nothing seems to work.

**Comment by thujohn** [comment]
Can you give me an example ?

**Comment by itsjustk** [comment]
Going a bit further it seems that PDF::load() does its job fine, but its when I use the output() is when things are going a bit wrong. 

In the image, the first block of text is just an echo of what output() does to the first PDF, after the border is the second PDF, it seems like there's just the usual PDF headers and not any actual content. 

![screenshot - 061213 - 12 51 00](https://f.cloud.github.com/assets/2310572/1692216/3ca1c634-5e75-11e3-97d3-eddeed9cf62b.png)

**Comment by thujohn** [comment]
I would say an example of your code :)

**Comment by itsjustk** [comment]
:D Sorry 
So this is the function I use to get the raw pdf data

```
$template = View::make('template.'.$template, array('will' => $this->bloatWillData($will->data), 'id' => $will->id))->render();

return PDF::load($template, 'A4', 'portrait');  
```

This works fine as many times as I call it in a row.

But when I try to output() it, using the data returned in the previous snippet for $pdf

```
file_put_contents($path, $pdf->output());
```

I get two files saved to my server, one PDF with my rendered view, but the second is just a blank PDF.

**Comment by itsjustk** [comment]
I seemed to have fixed this, but its a bit hacky as I think I'm bypassing the facade? 

In my class that generates the pdfs I entered the following: 

```
class WillManagement 
{
        /*
     * The Thujohn PDF object
     */
    protected $p;

    public function __construct()
    {
        $this->p = new Thujohn\Pdf\Pdf();
    }
```

And now instead of using 

```
PDF::load()
```

I use 

```
$this->p->load()
```

and it seems to solve whatever the problem is, **IF** I'm using one willmanagement object for each pdf

**Comment by thujohn** [comment]
I invite you to read this comment :) https://github.com/thujohn/pdf-l4/issues/22#issuecomment-28437889

I think you're trying to do the same thing ;)

**Comment by itsjustk** [comment]
The same solution for a different problem it seems! 

Thanks for getting back, and sorry I didn't see that solution before I bothered you, the issue was for a different error so i didn't click on it!

**Comment by thujohn** [comment]
I understand ;)
