### ISSUE TITLE
Call to undefined method DOMText::getAttribute

### ISSUE THREAD

**Issue by heidilux** [thujohn/pdf-l4#38]
In my controller I'm using:

```
public function savePDF($user, $order, $cust)
    {
        $html = View::make('pdfs.invoicePdf', compact('order', 'user', 'cust'))->render();
        $name = str_random(10) . '-invoice.pdf';
        File::put(public_path('pdfs/' . $name), PDF::load($html, 'A4', 'portrait')->output());
    }
```

When it's run, I'm getting a whoops screen with the following error:
![image](https://f.cloud.github.com/assets/5248157/2397662/25a64342-a9ed-11e3-9ce5-9b40dd286377.png)

The view does contain a bunch of tables as it is an invoice.  Could the empty `<td>`s give it trouble?

```
<tr>
    <td class="no-line"></td>
    <td class="no-line"></td>
    <td class="no-line text-center">Total</td>
    <td class="no-line text-right">${{ number_format($order->total_charged, 2) }}</td>
</tr>
```

Have you seen this particular error before?

**Comment by thujohn** [comment]
Did you try with `&nbsp;` ?

**Comment by heidilux** [comment]
Just tried.  No go.  Also tried just adding dummy text.  Must not be the `<td>`s.  My full blade file is here https://gist.github.com/heidilux/9518714  Not a very big file.  Any other ideas?  I'm able to get it to work when I use one of your examples... that is, just a very basic super simple `html` document, so it must be something about this particular html.

**Comment by heidilux** [comment]
Okay, it boiled down to an error on my part.  I'd forgotten  the `<tr>` withing the `<thead>`.  I went straight to `<td>`.  /facepalm...

Next on to figuring out how to include a style sheet...

Thanks for the quick response!
