### ISSUE TITLE
How to change settings? Changing default encoding?

### ISSUE THREAD

**Issue by ux-engineer** [thujohn/pdf-l4#4]
I need to use scandinavian alphabets (UTF-8)... I'm actually using the view object, only with "print" asset set (with Basset) and that charset should be declared in the HTML already. So the change must be done with the renderer. I'm using the download method.

Is there a way to publish settings to app/config via artisan?

**Comment by ux-engineer** [comment]
See this https://github.com/dompdf/dompdf/issues/626

**Comment by ux-engineer** [comment]
Fixed this issue here by changing in php.ini the mbstring encoding translation config line as: "mbstring.encoding_translation = On"!

**Comment by ux-engineer** [comment]
And the other question remains:

Could you create a way to publish settings so that when updating the package, the changes made under vendor folder wouldn't be overwritten, or actually asked by Composer what to do with that changed file every time update is run.

**Comment by thujohn** [comment]
Hi.

I didn't find a good way to exclude a file with composer and I think this is not a good choice to exclude a file from the original package.

For the moment I don't have solution but I still keep this in mind.

**Comment by bsweeney** [comment]
What I've found useful in the past is to provide a ".sample" file that shows how a configuration file should look. We're not currently doing this in dompdf, but we probably should. For example, `dompdf_custom_config.inc.php` should be renamed to `dompdf_custom_config.inc.php.sample`. The end user creates the dompdf_custom_config.inc.php file (either by creating one from scratch, copying the .sample file, or renaming the .sample file) when they want to customize their settings.

Whether or not this is viable depends on the project, but it should work for dompdf since that is basically the only file the user needs to modify.

**Comment by thujohn** [comment]
Finally I found a solution with `dompdf_custom.config.inc.php` but some constants can't be defined because they need constants defined after.

**Comment by bsweeney** [comment]
@thujohn not sure what you mean. Is that a dompdf problem or something else? Do you have an example?

**Comment by thujohn** [comment]
I added the content of `dompdf_custom.config.inc.php` in the config file and loaded the config before `dompdf_custom.config.inc.php`

I can't change DOMPDF_LOG_OUTPUT_FILE because DOMPDF_FONT_DIR is set after my config loaded.

**Comment by bsweeney** [comment]
@thujohn you should be able to set both of those from the custom config file. This is probably not the best place to work out the issue, though, since it is unrelated to the issue. Can you head over to the [support group](http://groups.google.com/group/dompdf) and start a new thread?

**Comment by ux-engineer** [comment]
How about making it Laravel package and being able to publish configs via artisan. Then tying those configs to that config file so it will remain static.

**Comment by thujohn** [comment]
@bsweeney You speak of dompdf or the package for dompdf ?

@envisio You can now publish config but you can't configurate everything. Take a look at the last commit.

**Comment by bsweeney** [comment]
Just dompdf.

**Comment by thujohn** [comment]
Ok we don't speak of the same thing.

Do you know if a portage to composer is planned ?

**Comment by bsweeney** [comment]
We have an initial implementation: https://packagist.org/packages/dompdf/dompdf

**Comment by thujohn** [comment]
When I'll have more time I'll check out your github
