### ISSUE TITLE
Persistent error with iconv_strlen()

### ISSUE THREAD

**Issue by fnfilho** [thujohn/pdf-l4#41]
Hey!
I'm getting a persistent error when executing this:

```
Route::get('/', function()
{
    $html = '<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/></head><body>'
            . '<p>Put your html here, or generate it with your favourite '
            . 'templating system.</p>'
            . '</body></html>';
    return PDF::load($html, 'A4', 'portrait')->show();
});
```

The error reads "iconv_strlen(): Wrong charset, conversion from `8bit//IGNORE' to`UCS-4LE' is not allowed", from file: /vendor/patchwork/utf8/class/Patchwork/PHP/Shim/Mbstring.php

Any ideas on what could be generating this?
I'm using L4.1 with Apache/2.2.26 and PHP 5.3.28

Thanks!

**Comment by thujohn** [comment]
Hi.

Did you check your php.ini ?

Else can you try to add :

```
iconv_set_encoding('internal_encoding', 'UTF-8');
iconv_set_encoding('input_encoding', 'UTF-8');
iconv_set_encoding('output_encoding', 'UTF-8');
```

**Comment by fnfilho** [comment]
Hey. Thanks for the reply.

I actually found the problem earlier, PHP didn't have mbstring active, it was just a matter of setting it up.
