### ISSUE TITLE
View::__toString() must not throw an exception

### ISSUE THREAD

**Issue by Bulmer** [thujohn/pdf-l4#49]
I've had PDF working on 2 other Servers (one Local Xampp and one Live) for 3 or 4 months with no worries. I have just moved my app to a new Server and am getting this error:
'Method Illuminate\View\View::__toString() must not throw an exception' in /home/***/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/dompdf.cls.php:0
Im just wondering if there is a PHP module or maybe a Permission problem? (Ive already set my /storage and subdirectories to 777.

**Comment by Bulmer** [comment]
Closing this -  it was caused by a value not being passed to the Blade View....

**Comment by cayu2008** [comment]
i have the same problem

**Comment by Bulmer** [comment]
From what I remember, this is the error you get when you're trying to display a value in your Blade View that you didn't pass from the Controller...
