### ISSUE TITLE
Page header/footer

### ISSUE THREAD

**Issue by esterisk** [thujohn/pdf-l4#52]
Hi, I have seen that dompdf creates automatically new pages as text flows, and this is great; I was wondering if there's any way to implement some page header/footer feature, or the page numbering. There are some css rules for that I think.

**Comment by thujohn** [comment]
Hi.

This issue seems to be the same : https://github.com/thujohn/pdf-l4/issues/44

**Comment by esterisk** [comment]
Thanks, I missed it.

**Comment by felipeblan** [comment]
esterisk How di you implemented the solution in your code? Thanks for your help.
