### ISSUE TITLE
Call to a member function prepend_child() on a non-object

### ISSUE THREAD

**Issue by dale-conroy** [thujohn/pdf-l4#55]
``` php
$view = View::make('account.order', array(
    'order' => Order::find($id)
));

return PDF::load($view, 'A4', 'portrait')->download('my_pdf');
```

```
[2014-07-29 22:25:08] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function prepend_child() on a non-object' in .../vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/frame_tree.cls.php:218
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
```

**Comment by thujohn** [comment]
Does this example works ?

``` php
Route::get('/', function()
{
    $html = '<html><body>'
            . '<p>Put your html here, or generate it with your favourite '
            . 'templating system.</p>'
            . '</body></html>';
    return PDF::load($html, 'A4', 'portrait')->download('my_pdf');
});
```

**Comment by dale-conroy** [comment]
Yes, it works when I use that, just not when I use my view.

**Comment by thujohn** [comment]
And if you try to only put this html (without parameters) in a view ?

**Comment by dale-conroy** [comment]
That also works as expected.

**Comment by thujohn** [comment]
If you return directly your view everything is good ?

**Comment by dale-conroy** [comment]
Yes, the view is displayed fine.

**Comment by thujohn** [comment]
I think there is a problem with your css (a before property).

Can you try without your css ?

**Comment by dale-conroy** [comment]
My template uses Bootstrap. It works when I do not use the template, so I assume the problem is what you expected, the CSS. Is there any way to fix this?

**Comment by thujohn** [comment]
Maybe you should try with the latest dompdf version : https://github.com/barryvdh/laravel-dompdf

**Comment by dale-conroy** [comment]
Is it possible to use the latest version with your code?

**Comment by thujohn** [comment]
You can create your own package with my code replacing the dompdf folder.

**Comment by dale-conroy** [comment]
Alright, thanks for your help.
