### ISSUE TITLE
Can I suggest an output option

### ISSUE THREAD

**Issue by sdsmith1981** [thujohn/pdf-l4#6]
So I can save the PDF to a file to attach/download later?

public function output($filename = 'dompdf_out', $options = array('compress' => 1, 'Attachment' => 1)){
        $this->render();
        return $this->dompdf->output($filename.'.pdf', $options);
    } 

would do it. Many thanks

**Comment by thujohn** [comment]
Just added the method output() :)

**Comment by sdsmith1981** [comment]
Many thanks, it'll be very useful to me!
