### ISSUE TITLE
Unable to stream pdf: headers already sent

### ISSUE THREAD

**Issue by jpilldev** [thujohn/pdf-l4#73]
Hi.

I download a pdf file from my dev server, everything goes fine, but, when i try to run in production, when i create the PDF file, i got an error: 

Unable to stream pdf: headers already sent

And there's no more message.
What can i do?

thanks.

**Comment by agencia** [comment]
could you share your code?

**Comment by jpilldev** [comment]
Hi Agencia.
The code is simple:

```
$html = View::make('pages.layout.user', $data);
            $headers = array('Content-Type' => 'application/pdf');
            return Response::make (PDF::load($html, 'A4', 'portrait')->download($user->code), 200, $headers);
```

Si, now, i saw the output of pages.layout.user,  and notice that the line that before header of PDF isanother line, i'm trying to catch it to remove (i don't remember when i printing that model path)

```
//app/model/User.php
%PDF-1.3
1 0 obj
<< /Type /Catalog
/Outlines 2 0 R
/Pages 3 0 R >>
.....
```

Thanks for help  ;)

**Comment by agencia** [comment]
this dev server of yours is windows? and then production is linux?

**Comment by jpilldev** [comment]
The server is Linux CentOS, the dev is Fedora

**Comment by agencia** [comment]
have you try this way? 

```
$html = View::make('pages.layout.user', $data);
PDF::load($html, 'A4', 'portrait')->download($user->code);
```

That error means your headers are not rigth

**Comment by jpilldev** [comment]
The same output.

So, a PDF file must begin with the chars %PDF-1.3 ..., but my app places another line before that chars

```
//app/model/User.php
%PDF-1.3
1 0 obj
<< /Type /Catalog
/Outlines 2 0 R
/Pages 3 0 R >>
.....
```

So, i don't rememberwhere i code the print of that path (//app/model/User.php), so i trying to debug and remove that line.
Thanks

**Comment by agencia** [comment]
ah, thats it, you shouldn't be printing vars, query or paths on production, try to use logging

http://laravel.com/docs/4.2/errors#logging

**Comment by jpilldev** [comment]
Right now i haven't Logging for laravel, So, a newbie question, can i use to determine the file that is printing that path?

Thanks again

**Comment by agencia** [comment]
that depends on your IDE, in Sublime I user "Find in files", what IDE are you using?

**Comment by jpilldev** [comment]
I'm in netbeans (please don't hate me), in the moment i needed that ide, so, i will continue to find that code.

Thanks again

**Comment by agencia** [comment]
thats ok actually i like netbeans.
 try
Menu edit >> find in projects >> write "app/model/User.php" in the containing text field

**Comment by jpilldev** [comment]
Ok agencia, you are a Hero, it was a very simple solution to an all day problem, that line was in the first line of the model file.

Thanks a lot.

**Comment by agencia** [comment]
no problem, could you close this issue?
