### ISSUE TITLE
How to set configuration?

### ISSUE THREAD

**Issue by Maximebpro** [thujohn/pdf-l4#77]
I've been looking for way to set 
    def("DOMPDF_ENABLE_REMOTE", true);
in my Laravel config

I've seen in the Pdf class

```
    $_conf = array('DOMPDF_TEMP_DIR', 'DOMPDF_UNICODE_ENABLED', ...);

    foreach ($_conf as $conf){
        if ((Config::has('pdf::'.$conf) || Config::get('pdf::'.$conf)) && !defined($conf))
            define($conf, Config::get('pdf::'.$conf));
    }
```

I've never seen the the "pdf::" notation. Every example I can find is "app.something.somethingelse". How you use "pdf::something"? Should I create a pdf.php in config folder?

Could you please provide an example in your README to set this up?

Thank you for this great lib :)

**Comment by thujohn** [comment]
Hi.

You need to publish and edit the config file

`php artisan config:publish thujohn/pdf`

**Comment by Maximebpro** [comment]
Which config file and what's the format?

I've been using `define('DOMPDF_ENABLE_REMOTE', true);` which works but I'd rather use the config file.

**Comment by thujohn** [comment]
After publishing you will find the config file here : `/app/config/packages/thujohn/pdf/config.php`

**Comment by Maximebpro** [comment]
It works ! Thank you.
