### ISSUE TITLE
Change config settings

### ISSUE THREAD

**Issue by sdsmith1981** [thujohn/pdf-l4#8]
It doesn't seem possible to change config settings like DOMPDF_ENABLE_REMOTE via a config file. They appear to be overwritten in dompdf_config.inc.php

**Comment by thujohn** [comment]
Dompdf doesn't and can't overwrite a constant.
In the dompdf config file every constants are defined with def() that check the definition.

The problem is Config::has() doesn't take a "true" value.

Now the problem is solved. Thank you for your report.
