### ISSUE TITLE
Enhancement: The ability to fetch a parsed template

### ISSUE THREAD

**Issue by mikerockett** [thujohn/pdf-l4#9]
This looks cool enough, but I think a developer should be able to provide the package with the name of a view which needs to be parsed, instead of using HTML in the controller.

So, one would call `PDF::load('invoice', ...)->show();`

The package would then check to see if the string provided is a view, and then render the PDF based upon its results. If it isn't a view, then render it as normal.

Or, maybe even better: `PDF::load('view:invoice' ...)->show();`

**Comment by thujohn** [comment]
Hi.

You can do already do that :

``` php
return PDF::load(View::make('view', $data), 'A4', 'portrait')->show();
```

**Comment by mikerockett** [comment]
Also true - my bad...
