### ISSUE TITLE
PDF Output Gibberish 

### ISSUE THREAD

**Issue by neutt22** [thujohn/pdf-l4#95]
Note that this is working on my local environment. But when I've uploaded my site this is what shows up instead of the PDF:
<img src="http://s19.postimg.org/52hwj3j2b/Untitled.png"/>

Can someone shed somelight what is happening? No logs detected though.

**Comment by neutt22** [comment]
Also note that I'm sure I have uploaded all the files and directories of the Laravel app especially the vendor directory.

Thanks!

**Comment by tonijn** [comment]
+1

**Comment by josephilipraja** [comment]
Running a `chmod -R 777 vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/` seems to fix it for me!
Apparently **dompdf** needs write permissions to generate PDF on the fly..

**Comment by neutt22** [comment]
@josephilipraja im using L5 right now and everything seems okay now :)
